language: java
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS everdonate;'
  - mysql -e 'USE everdonate;'
  - mysql -u root --password="" < src/main/resources/data.sql